'use strict';
/**
    Namespace for LZW compression and decompression.
    Methods:
        LZW.compress(uncompressed)
        LZW.decompress(compressed)
*/
export default class LZW {
    /**
        Perform the LZW compression
        uncompressed - String. The string on which to perform the compression.
    */
    static encode(uncompressed: string) {
        // Initialize dictionary
        let dictionary: { [key: string]: number } = {};
        for (let i = 0; i < 256; i++) {
            dictionary[String.fromCharCode(i)] = i;
        }

        let word = '';
        let result: number[] = [];
        let dictSize = 256;

        for (let i = 0, len = uncompressed.length; i < len; i++) {
            let curChar = uncompressed[i];
            let joinedWord = word + curChar;

            // Do not use dictionary[joinedWord] because javascript objects
            // will return values for myObject['toString']
            if (dictionary.hasOwnProperty(joinedWord)) {
                word = joinedWord;
            }
            else {
                result.push(dictionary[word]);
                // Add wc to the dictionary.
                dictionary[joinedWord] = dictSize++;
                word = curChar;
            }
        }

        if (word !== '') {
            result.push(dictionary[word]);
        }

        return result;
    }

    /**
        Decompress LZW array generated by LZW.compress()
        compressed - Array. The array that holds LZW compressed data.
    */
    static decode(compressed: number[]) {
        // Initialize Dictionary (inverse of compress)
        let dictionary: { [key: number]: string } = {};
        for (let i = 0; i < 256; i++) {
            dictionary[i] = String.fromCharCode(i);
        }

        let word = String.fromCharCode(compressed[0]);
        let result = word;
        let entry = '';
        let dictSize = 256;

        for (let i = 1, len = compressed.length; i < len; i++) {
            let curNumber = compressed[i];

            if (dictionary[curNumber] !== undefined) {
                entry = dictionary[curNumber];
            }
            else {
                if (curNumber === dictSize) {
                    entry = word + word[0];
                }
                else {
                    throw 'Error in processing';
                }
            }

            result += entry;

            // Add word + entry[0] to dictionary
            dictionary[dictSize++] = word + entry[0];

            word = entry;
        }

        return result;
    }
}

function test () {
    let starting = {
        'test': 'test',
        'test2': 'test2',
        'test3': 'test3',
        'test4': 'test4',
        'test5': {
            'test': 'test',
            'test2': 'test2',
        }
    }
    console.log('starting', starting);
    let compressed = LZW.encode(
        JSON.stringify(starting)
    );
    let decompressed = JSON.parse(LZW.decode(compressed));
    console.log('compressed', compressed);
    console.log('decompressed', decompressed);
}

test()
